testing parallel jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,83 +11,104 @@ on:
   workflow_dispatch:
 
 jobs:
-  e2e-tests:
+  # e2e-tests:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+
+  #     - name: Set up Node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16
+  #         cache: "npm"
+
+  #     - name: NPM Install
+  #       run: npm ci
+
+  #     - name: Execute WDIO Tests
+  #       run: npm run test
+
+  #     - name: Upload Report Artifacts
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: reports
+  #         path: |
+  #           reports/*.xml
+  #           allure-results/*.xml
+  #           allure-results/*.png
+  #           screenshots/*png
+
+  #     - name: Display JUnit Report
+  #       uses: phoenix-actions/test-reporting@v8
+  #       id: junit-reports
+  #       if: success() || failure()
+  #       with:
+  #         name: WebdriverIO Junit Reports
+  #         path: reports/*.xml
+  #         reporter: jest-junit
+  #         list-suites: all
+  #         list-tests: all
+  #         max-annotations: 10
+  #         fail-on-error: true
+
+  #     - name: Get Allure history
+  #       uses: actions/checkout@v2
+  #       if: always()
+  #       continue-on-error: true
+  #       with:
+  #         ref: gh-pages
+  #         path: gh-pages
+
+  #     - name: Generate Allure Report
+  #       uses: simple-elf/allure-report-action@master
+  #       if: always()
+  #       id: allure-report
+  #       with:
+  #         allure_results: allure-results
+  #         allure_report: allure-report
+  #         gh_pages: gh-pages
+  #         allure_history: allure-history
+
+  #     - name: Deploy report to Github Pages
+  #       if: always()
+  #       uses: peaceiris/actions-gh-pages@v2
+  #       env:
+  #         PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         PUBLISH_BRANCH: gh-pages
+  #         PUBLISH_DIR: allure-history
+
+  #     - name: Post the link to the report
+  #       if: always()
+  #       uses: Sibz/github-status-action@v1
+  #       with:
+  #         authToken: ${{secrets.GITHUB_TOKEN}}
+  #         context: "Test report"
+  #         description: "Passed"
+  #         state: "success"
+  #         sha: ${{github.event.pull_request.head.sha || github.sha}}
+  #         target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
+
+  matrix-tests:
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+      max-parallel: 2
+      matrix:
+        run: ["av_prod.spec.js", "g4m_prod.spec.js"]
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+    - name: Checkout
+      uses: actions/checkout@v3
 
-      - name: Docker Compose
-        run: docker-compose up --abort-on-container-exit
+    - name: Set up Node
+      uses: actions/setup-node@v3
+      with:
+        node-version: 16
+        cache: "npm"
 
-      # - name: Set up Node
-      #   uses: actions/setup-node@v3
-      #   with:
-      #     node-version: 16
-      #     cache: "npm"
+    - name: NPM Install
+      run: npm ci
 
-      # - name: NPM Install
-      #   run: npm ci
+    - name: Execute WDIO Tests
+      - run: npm test -- --spec=./tests/${{ matrix.run }}
 
-      # - name: Execute WDIO Tests
-      #   run: npm run test
-
-      # - name: Upload Report Artifacts
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: reports
-      #     path: |
-      #       reports/*.xml
-      #       allure-results/*.xml
-      #       allure-results/*.png
-      #       screenshots/*png
-
-      # - name: Display JUnit Report
-      #   uses: phoenix-actions/test-reporting@v8
-      #   id: junit-reports
-      #   if: success() || failure()
-      #   with:
-      #     name: WebdriverIO Junit Reports
-      #     path: reports/*.xml
-      #     reporter: jest-junit
-      #     list-suites: all
-      #     list-tests: all
-      #     max-annotations: 10
-      #     fail-on-error: true
-
-      # - name: Get Allure history
-      #   uses: actions/checkout@v2
-      #   if: always()
-      #   continue-on-error: true
-      #   with:
-      #     ref: gh-pages
-      #     path: gh-pages
-
-      # - name: Generate Allure Report
-      #   uses: simple-elf/allure-report-action@master
-      #   if: always()
-      #   id: allure-report
-      #   with:
-      #     allure_results: allure-results
-      #     allure_report: allure-report
-      #     gh_pages: gh-pages
-      #     allure_history: allure-history
-
-      # - name: Deploy report to Github Pages
-      #   if: always()
-      #   uses: peaceiris/actions-gh-pages@v2
-      #   env:
-      #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     PUBLISH_BRANCH: gh-pages
-      #     PUBLISH_DIR: allure-history
-
-      # - name: Post the link to the report
-      #   if: always()
-      #   uses: Sibz/github-status-action@v1
-      #   with:
-      #     authToken: ${{secrets.GITHUB_TOKEN}}
-      #     context: "Test report"
-      #     description: "Passed"
-      #     state: "success"
-      #     sha: ${{github.event.pull_request.head.sha || github.sha}}
-      #     target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
